spring:
  application:
    name: authentication-model-demo
  datasource:
    url: jdbc:h2:mem:authdemo;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  port: 8080
