// `record` (Java 16+) generates equals, hashCode, toString, and accessors
// from a single one-line declaration. Perfect for value objects / DTOs.

import java.util.HashSet;
import java.util.Set;

record User(String name, int age) { }

public class RecordAutoGenerated {
    public static void main(String[] args) {
        User a = new User("Alice", 30);
        User b = new User("Alice", 30);

        // toString — generated. Concise and informative.
        System.out.println("a = " + a);     // User[name=Alice, age=30]

        // Accessors — name() and age(), NOT getName/getAge.
        System.out.println("a.name() = " + a.name());
        System.out.println("a.age()  = " + a.age());

        // equals — value-based, generated.
        System.out.println("a.equals(b): " + a.equals(b));      // true

        // hashCode — also value-based; works correctly in hashed collections.
        Set<User> users = new HashSet<>();
        users.add(a);
        System.out.println("Set contains b: " + users.contains(b));   // true

        // Records are also IMMUTABLE — fields are final, no setters generated.
        // Perfect for DTOs, value objects, and most "just-data" classes.
    }
}
